import Navbar from "@/components/Ui/Navbar";
import AuthProvider from "@/providers/AuthProvider";
import { dbConnect } from "@/services/mongo";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Eventry - Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar />
          <main class="py-8">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
